law/urls.py
from django.contrib import admin
from django.conf.urls import url, include

urlpatterns = [
    url(r'admin/', admin.site.urls),
    url(r'^', include('web.urls')),
    url(r'^', include('apply.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
]

main_page/models.py
from django.db import models
from tinymce.models import HTMLField


class Faq(models.Model):
    question = models.TextField(max_length=256, blank=True, null=True, default=None)
    answer = HTMLField()

    def __str__(self):
        return '%s' % self.question

    class Meta:
        verbose_name = 'FAQ'
        verbose_name_plural = 'FAQ'


class Replies(models.Model):
    name = models.CharField(max_length=64, blank=True, null=True, default=None)
    subj = models.CharField(max_length=128, blank=True, null=True, default=None)
    text = HTMLField()
    video_iframe = models.TextField(max_length=512, blank=True, null=True, default=None)

    def __str__(self):
        return '%s' % self.name

    class Meta:
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'


class RepliesImg(models.Model):
    reply = models.ForeignKey(Replies, blank=True, null=True, default=None, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='static/img/replies')

    def __str__(self):
        return '%s' % self.id

    class Meta:
        verbose_name = 'Фото на отзыв'
        verbose_name_plural = 'Фото на отзывы'


class PriceHead(models.Model):
    title = models.TextField(max_length=124, blank=True, null=True, default=None)

    def __str__(self):
        return '%s' % self.title

    class Meta:
        verbose_name = 'Цены, категория'
        verbose_name_plural = 'Цены, категории'


class Prices(models.Model):
    prices_cat = models.ForeignKey(PriceHead, blank=True, null=True, default=None, on_delete=models.CASCADE)
    subj = models.TextField(max_length=256, blank=True, null=True, default=None)
    price = models.CharField(max_length=24, blank=True, null=True, default=None)

    def __str__(self):
        return '%s' % self.subj

    class Meta:
        verbose_name = 'Цена'
        verbose_name_plural = 'Цены'


class Stuff(models.Model):
    name = models.CharField(max_length=56, blank=True, null=True, default=None, verbose_name=u"Имя")
    job = models.CharField(max_length=56, blank=True, null=True, default=None, verbose_name=u"Должность")
    e1 = HTMLField(default=None, verbose_name=u"Дополнительное поле 1 (стаж)")
    e2 = HTMLField(default=None, verbose_name=u"Дополнительное поле 2 (выиграно дел)")
    e3 = HTMLField(default=None, verbose_name=u"Дополнительное поле 3 (отрасль)")
    text = HTMLField(default=None, verbose_name=u"Текст")


class StuffImg(models.Model):
    stuff = models.ForeignKey(Stuff, blank=True, null=True, default=None, on_delete=models.CASCADE)
    img = models.ImageField(upload_to='static/img/stuff')

templates/site/about.html
{% load static %}
{% include 'site/head.html' %}
	<nav>
		<div class="container">
			<ul class="navigation">
				<li class="a1"><a href="/#services">Наши услуги</a></li>
				<li class="a2"><a href="/#prices">Цены</a></li>
				<li><a href="">Полезные статьи</a></li>
				<li class="a3"><a href="/#replies">Отзывы</a></li>
				<li class="active-nav"><a href="/about">О компании</a></li>
				<li><a href="/contacts">Контакты	</a></li>
			</ul>
		</div>
	</nav>
	<section class="about">
		<div class="container">
			<h2>О нашей <b>компании</b></h2>
			<div class="line"></div>
			<p>Компания СпецЮст предоставляет юридические услуги в сфере недвижимости и решения земельных вопросов, гражданского и арбитражного судопроизводства, а также в сфере архитектурного проектирования. К нам обращаютя частные и юридические лица. <br><br>Наша компания находится на рынке более 5 лет, за это время мы выйграли свыше 1380 дел, помогли более 750 предпринимателям и выполниле свыше 900 проектов различной сложности. <br><br>Данный опыт позволил выработать системность решения поступающих проблем наших клиентов. В нашей работе задействованы узкопрофильные специалисты, что позволяет добиться максимально эффективного результата в заданные сроки.  </p>
		</div>
	</section>
	<section class="dark-bg stuff">
		<div class="stuff-bg"><img src="{% static 'img/stuff-bg.png' %}" alt=""/></div>
		<div class="container">
			<h2>В нашей компании работают <b>узконаправленные специалисты</b> для каждой конкретной ситуации</h2>
			<div class="line"></div>
			<p class="descriptor">Опыт работы каждого нашего специалиста в своем сегменте более 5 лет. <br>Наша команда выигрывает ежегодно свыше 270 дел. За последние 2 года наша статистика показывает удельный вес выйграных дел в 93%</p>
			<div class="stuff-block clearfix">
				<div class="stuff-menu">
                    {% for stuff_item in stuff %}
					<div class="stuff-tab">
						<div class="stuff-tab-img"><img src="{{ stuff_item.img.url }}" alt=""/></div>
						<p><b>{{ stuff_item.stuff.name }}</b> <br>{{ stuff_item.stuff.job }}</p>
					</div>
                    {% endfor %}
				</div>
				<div class="stuff-items owl-carousel">
                    {% for stuff_item in stuff %}
					<div class="stuff-item">
						<div class="stuff-item-img"><img src="{{ stuff_item.img.url }}" alt=""/></div>
						<p class="name">{{ stuff_item.stuff.name }}</p>
						<div class="line-1"></div>
						<p class="job">{{ stuff_item.stuff.job }}</p>
						<div class="line-2"></div>
						<div class="stuff-flex">
							<p>{{ stuff_item.stuff.e1|safe }}</p>
							<p>{{ stuff_item.stuff.e2|safe }}</p>
							<p>{{ stuff_item.stuff.e3|safe }}</p>
						</div>
						<div class="line-2"></div>
						<p class="say">{{ stuff_item.stuff.text|safe }}</p>
					</div>
                    {% endfor %}
				</div>
			</div>
			<p class="descriptor-2">   Вы всегда можете рассчитывать на подробную консультацию от наших специалистов. <br>Мы обладаем профессиональными знаниями и огромным опытом в сфере предоставляемых нами услуг. Подробно расскажем обо всех тонкостях судебного процесса и решения споров.</p>
		</div>
	</section>
	<section class="work">
		<div class="container">
			<h2>Как мы оптимизировали <b>рабочий процесс</b></h2>
			<div class="line"></div>
			<div class="work-flex">
				<div class="work-item">
					<p>К нам поступает большой поток клиентов по одним и тем же вопросам с аналогичными ситуациями. Благодаря этому мы вырыботали определенную систему, которая позволяет ускорить решение поступивших проблем клиентов и экономить их финансовые затраты</p>
				</div>
				<div class="work-item">
					<p>Для каждого клиента мы назначаем компетентного специалиста по решению его проблемы. В случае, если задача многостороннего характера, то подключаются дополнительные специалисты  </p>
				</div>
				<div class="work-item">
					<p>Мы подключили в работу только проверенных временем и постоянным взаимодействием нотариусов, с ними ведется налаженный процесс подачи и обработки заявок в режиме Online, что экономит время подготовки к сделкам  </p>
				</div>
			</div>
		</div>
	</section>
{% include 'site/footer.html' %}

templates/site/contacts.html
{% load static %}
{% include 'site/head.html' %}
	<nav>
		<div class="container">
			<ul class="navigation">
				<li class="a1"><a href="/#services">Наши услуги</a></li>
				<li class="a2"><a href="/#prices">Цены</a></li>
				<li><a href="">Полезные статьи</a></li>
				<li class="a3"><a href="/#replies">Отзывы</a></li>
				<li><a href="/about">О компании</a></li>
				<li class="active-nav"><a href="/contacts">Контакты	</a></li>
			</ul>
		</div>
	</nav>
	<section class="contacts">
		<div class="container">
			<h2>Наши <b>контакты</b></h2>
			<div class="line"></div>
			<div class="contacts-block">
				<div class="contacts-item"><img src="{% static 'img/c1.png' %}" alt=""/>
					<h5>Телефон</h5>
					<p>Многоканальный телефон: <b>8-800-8000-000</b> <br>Мобильный телефон: <b>8-922-8000-222</b></p>
				</div>
				<div class="contacts-item"><img src="{% static 'img/c2.png' %}" alt=""/>
					<h5>Электронная почта</h5>
					<p>Проекты, заявки и вопросы высылайте на адрес: <b>info_moszem@mail.ru</b></p>
				</div>
				<div class="contacts-item"><img src="{% static 'img/c3.png' %}" alt=""/>
					<h5>График работы</h5>
					<p>пн-пт с 10.00 до 20.00, cб с 11.00 до 19.00 <br>вс - выходной  </p>
				</div>
				<div class="contacts-item"><img src="{% static 'img/c4.png' %}" alt=""/>
					<h5>Адрес</h5>
					<p>Наш офис находится по адресу: <br><b>пр. Маршала жукова, корпус 1</b></p>
				</div>
			</div>
			<p>В наш офис Вы можете приехать в любое рабочее время либо по договоренности. <br>В офисе всегда находится дежурный специалист, который проведет для Вас бесплатную консультацию, озвучит сроки решения Вашего вопроса, предоставит перечень необходимых докуменнтов и рассчитает стоимость по предоставлению наших услуг конкретно по Вашей ситуации.</p>
		</div>
		<div class="map"><script type="text/javascript" charset="utf-8" async src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3Affce56b8a067e18b15eb19231779e90755717cb9cdc6742eef14225bea609842&amp;width=100%&amp;height=100%&amp;lang=ru_RU&amp;scroll=false"></script></div>
	</section>
	<section class="catch-form">
		<div class="catch-form-bg"><img src="{% static 'img/catch-bg.png' %}" alt=""/></div>
		<div class="container">
			<h2><b>Остались вопросы?</b></h2>
			<div class="line"></div>
			<p class="description">Получите бесплатную развёрнутую консультацию специалиста</p>
			<div class="catch-block clearfix">
				<div class="catch-left">
					<form action="{% url 'apply' %}" method="post">
						<input type="text" name="name" placeholder="Введите имя" required="required"/>
						<input type="text" name="phone" placeholder="Введите телефон" required="required"/>
						<textarea name="text" placeholder="Опишите вашу проблему"></textarea>
                        {% csrf_token %}
                        <input type="hidden" name="type" value="Заявка на обратный звонок">
						<button class="button">Заказать консультацию</button>
					</form>
				</div>
				<div class="catch-right">
					<h5>Вам ответит специалист <br>и проведет полную консультацию <br>по вашему вопросу  </h5>
					<ul>
						<li>Предоставит Вам оптимальный расчёт цены</li>
						<li>Сориентирует по срокам</li>
						<li>Раскажет как правильно сформировать пакет документов</li>
						<li>Даст полное описание процесса</li>
					</ul>
				</div>
			</div>
		</div>
	</section>
{% include 'site/footer.html' %}

templates/site/footer.html
{% load static %}
<footer>
		<div class="footer-bg"><img src="{% static 'img/footer-bg.png' %}" alt=""/></div>
		<div class="container">
			<ul class="menu-1">
                {% for service in services %}
				<li><a href="{% url 'service' service.category.url_name %}">{{ service.category.name }}</a></li>
                {% endfor %}
			</ul>
{#			<ul class="menu-2">#}
{#				<li><a href="">Жилая застройка</a></li>#}
{#				<li><a href="">Объекты торговли</a></li>#}
{#				<li><a href="">Административные объекты</a></li>#}
{#				<li><a href="">Объекты рекреации</a></li>#}
{#				<li><a href="">Складские и промышленые </a></li>#}
{#				<li><a href="">Автотранспортные предприятия</a></li>#}
{#			</ul>#}
			<div class="footer-form"><img src="{% static 'img/logo.png' %}" alt=""/>
				<p>Есть вопросы? Звоните <br><b>+7 981 914 42 34</b></p>
				<button class="button shadow-button call" data-type="Заявка на обратный звонок">Заказать звонок</button>
				<div class="footer-flex"><a href=""><img src="{% static 'img/vk.png' %}" alt=""/></a><a href=""><img src="{% static 'img/twitter.png' %}" alt=""/></a><a href=""><img src="{% static 'img/fb.png' %}" alt=""/></a></div>
			</div>
		</div>
	</footer>
	<div class="politics">
		<div class="container"><a href="">МОСЗЕМКОМ - Владивосток и Приморский край</a><a href="">Политика конфиденциальности</a></div>
	</div>
	<div class="layer">
		<div class="callback popup"><img src="{% static 'img/close.png' %}" class="close"/>
			<h6>Оставьте свои данные</h6>
			<form action="{% url 'apply' %}" method="post">{% csrf_token %}
				<input type="text" name="name" placeholder="Ваше имя" required="required"/>
				<input type="text" name="phone" placeholder="Ваш телефон" required="required"/>
                <input type="hidden" name="type" value="Заявка на обратный звонок">
				<button class="button">Отправить</button>
			</form>
			<p>В течение 10 минут с вами свяжется наш специалист и предоставит развёрнутую консультацию</p>
		</div>
        <div class="thank">
            <p>Спасибо за сотрудничество!</p>
            <p>Мы свяжемся с вами в ближайшее время.</p>
        </div>
	</div>
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
	<script src="{% static 'libs/owl-carousel/owl.carousel.min.js' %}"></script>
	<script src="{% static 'libs/Swiper-4.0.6/dist/js/swiper.min.js' %}"></script>
	<script src="{% static 'libs/jquery-nice-select-1.1.0/js/jquery.nice-select.min.js' %}"></script>
	<script src="{% static 'js/mask.js' %}"></script>
	<script src="{% static 'js/main.js' %}"></script>
</body>

templates/site/head.html
{% load static %}
<!DOCTYPE html>
<html lang="en"></html>
<head>
	<meta charset="UTF-8"/>
	<title>{% if serv.name %}{{ serv.name }}{% else %}Главная | Юридические услуги{% endif %}</title>
    <meta name="keywords" content="{% if serv.meta_tags %}{{ serv.meta_tags }}{% else %}юридические услуги, владивосток, приморский край{% endif %}" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
	<link rel="stylesheet" href="{% static 'libs/bootstrap/bootstrap-grid-3.3.1.min.css' %}"/>
	<link href="{% static 'libs/owl-carousel/owl.carousel.css' %}" rel="stylesheet"/>
	<link href="{% static 'libs/Swiper-4.0.6/dist/css/swiper.css' %}" rel="stylesheet"/>
	<link href="{% static 'libs/jquery-nice-select-1.1.0/css/nice-select.css' %}" rel="stylesheet"/>
	<link href="{% static 'css/fonts.css' %}" rel="stylesheet"/>
	<link href="{% static 'css/normalize.css' %}" rel="stylesheet"/>
	<link href="{% static 'css/main.css' %}" rel="stylesheet"/>
	<link href="{% static 'css/media.css' %}" rel="stylesheet"/>
</head>
<body>
	<header>
		<div class="container">
            <a href="/">
                <img src="{% static 'img/logo.png' %}" class="logo"/>
            </a>
			<div class="address"><div class='h-img'><img src="{% static 'img/h1.png' %}" /></div> г. Владивосток.  Ул. Мира д.78 <br><div class='h-img'><img src="{% static 'img/h2.png' %}" /></div> info@moszem.com</div>
			<button class="button call" data-type="Заявка на обратный звонок">Заказать звонок</button>
			<div class="phone"><div class='h-img'><img src="{% static 'img/h3.png' %}" /></div> Работаем с 9:00 до 22:00 <br><div class='h-img'><img src="{% static 'img/h4.png' %}" /></div> +7 981 947 06 82</div>
		</div>
	</header>

templates/site/index.html
{% load static %}
{% include 'site/head.html' %}
	<nav>
		<div class="container">
			<ul class="navigation">
				<li class="active-nav a1"><a href="/#services">Наши услуги</a></li>
				<li><a href="/#prices" class="a2">Цены</a></li>
				<li><a href="">Полезные статьи</a></li>
				<li><a href="/#replies" class="a3">Отзывы</a></li>
				<li><a href="/about">О компании</a></li>
				<li><a href="/contacts">Контакты</a></li>
			</ul>
		</div>
	</nav>
	<section class="main">
		<div class="main-bg"><img src="{% static 'img/main-bg.png' %}"/></div>
		<div class="container">
			<div class="main-left">
				<h1>Компания <span>«СпецЮст»</span> занимается решением юридических вопросов связанных с  недвижимостью, гражданским и арбитражным судопроизводством</h1>
				<ul>
					<li>
						<div class="main-left-img"><img src="{% static 'img/m1.png' %}" alt=""/></div><span>Регистрация недвижимости</span>
					</li>
					<li>
						<div class="main-left-img"><img src="{% static 'img/m2.png' %}" alt=""/></div><span>Гражданское и арбитражное судопроизводство</span>
					</li>
					<li>
						<div class="main-left-img"><img src="{% static 'img/m3.png' %}" alt=""/></div><span>Кадастровые работы и инженерные изыскания</span>
					</li>
					<li>
						<div class="main-left-img"><img src="{% static 'img/m4.png' %}" alt=""/></div><span>Перевод земель</span>
					</li>
				</ul>
			</div>
			<div class="main-right">
				<h5>Оставьте заявку на бесплатную консультацию</h5>
				<form action="{% url 'apply' %}" method="post">{% csrf_token %}
					<input type="text" name="name" placeholder="Введите имя" required="required"/>
					<input type="text" name="phone" placeholder="Введите телефон" required="required"/>
                    <input type="hidden" name="type" value="Заявка на обратный звонок">
					<button class="button">Получить консультацию</button>
				</form>
				<p>В течение 10 минут с  вами свяжется наш специалист и предоставит развёрнутую консультацию </p>
			</div>
		</div>
	</section>
	<section class="services" id="services">
		<div class="container">
			<h2><b>Выберите</b> интересующую вас услугу</h2>
			<div class="line"></div>
			<div class="services-flex">
                {% for service in services %}
                <a href="{% url 'service' service.category.url_name %}" class="services-item">
					<div class="service-img"><img src="{{ service.image.url }}"/></div>
					<p>{{ service.category.name }}</p>
                </a>
                {% endfor %}
            </div>
		</div>
	</section>
	<section class="prices-main" id="prices">
		<div class="container">
			<h2><b>Стоимость</b> услуг</h2>
			<div class="line"></div>
			<p class="description">Обращаем  внимание что стоимость оформления рассчитывается в индивидуальном порядке.</p>
			<div class="prices-main__block">
                {% for price_head in prices %}
				<div class="price-main__item">
					<div class="price-main__head">
						<h5>{{ price_head.title }}</h5>
						<button class="button-price">Подробнее</button>
					</div>
					<div class="price-main__body">
						<div class="line-body"></div>
						<table>
                            {% for price in price_head.prices_set.all %}
							<tr>
								<td>{{ price.subj }}</td>
								<td>От <span>{{ price.price }} р.</span></td>
							</tr>
                            {% endfor %}
						</table>
					</div>
				</div>
                {% endfor %}
            </div>
		</div>
	</section>
	<section class="advances dark-bg">
		<div class="advances-bg"><img src="{% static 'img/adv-bg.png' %}" alt=""/></div>
		<div class="container">
			<h2>Выбирая нашу компанию вы получаете <b>ряд преимуществ</b></h2>
			<div class="line"></div>
			<div class="advances-block clearfix">
				<div class="advances-left">
					<div class="advances-item">
						<h4><div class='advance-img'><img src="{% static 'img/a1.png' %}" /></div> <span>Снимаем с вас трудности и проблемы</span></h4>
						<p>Не нужно тратить время, ждать в очередях и разбираться в юридических тонкостях. <br>Мы сделаем это за вас </p>
					</div><img src="{% static 'img/adv.png' %}" alt="" class="adv-img"/>
				</div>
				<div class="advances-right-flex">
					<div class="advances-item">
						<h4><div class='advance-img'><img src="{% static 'img/a2.png' %}" /></div> <span>Гибкий формат рассчёта <br>и доступные цены</span></h4>
						<p>Программа оптимизации цен и система обслуживания клиентов позволяет сэкономить деньги и время </p>
					</div>
					<div class="advances-item">
						<h4><div class='advance-img'><img src="{% static 'img/a3.png' %}" /></div> <span>Компетентные специалисты</span></h4>
						<p>У нас работают узкопрофильные специалисты, что дает максимальную эффективность </p>
					</div>
					<div class="advances-item">
						<h4><div class='advance-img'><img src="{% static 'img/a4.png' %}" /></div> <span>Каждая сделка застрахована</span></h4>
						<p>Мы несем юридическую и материальную ответственность за каждую заключенную нами сделку</p>
					</div>
					<div class="advances-item">
						<h4><div class='advance-img'><img src="{% static 'img/a5.png' %}" /></div> <span>Более 5 лет на рынке</span></h4>
						<p>Более 5 лет на рынке. Стабильное и успешное выполнение задач любой сложности</p>
					</div>
					<div class="advances-item">
						<h4><div class='advance-img'><img src="{% static 'img/a6.png' %}" /></div> <span>Бесплатная консультация при обращении</span></h4>
						<p>При первом звонке Вы получите первичное консультирование от специалиста, ориентирование по срокам, перечень необходимых документов и порядок ценообразования </p>
					</div>
					<div class="advances-item">
						<h4><div class='advance-img'><img src="{% static 'img/a1.png' %}" /></div> <span>Работа с частными и юридическими лицами</span></h4>
						<p>Предоставляем бесплатную развернутую консультацию каждому клиенту</p>
					</div>
				</div>
			</div>
		</div>
	</section>
	<section class="faq">
		<div class="container faq-top"><img src="{% static 'img/f.png' %}" alt=""/>
			<h3><b>Ответы на вопросы</b> <br>наших клиентов</h3>
			<p class="desc">Мы <b>собрали</b> для вас список <br>самых актуальных вопросов <br>и <b>ответили</b> на них</p>
		</div>
		<div class="container">
			<div class="faq-slider owl-carousel">
                {% for faq in faqs %}
				<div class="faq-slide">
					<div class="faq-head"><span class="faq-q"><img src="{% static 'img/question.png' %}" alt=""/></span>
						<p>{{ faq.question }}</p>
					</div>
					<div class="faq-body">
						<p>{{ faq.answer|safe }}</p>
					</div>
				</div>
                {% endfor %}
			</div>
		</div>
	</section>
	<section class="replies" id="replies">
		<div class="container">
			<h2><b>Клиенты</b> о нас</h2>
			<div class="line"></div>
			<div class="replies-slider owl-carousel">
                {% for reply in replies %}
				<div class="replies-slide">
					<div class="reply-top clearfix">
						<h5>{{ reply.reply.name }}</h5>
						<h6>{{ reply.reply.subj }}</h6>
					</div>
					<div class="reply-body clearfix">
						<div class="reply-img"><img src="{{ reply.image.url }}" alt=""/></div>
						<div class="reply-right">
							<p>{{ reply.reply.text|safe }}</p>
							<button class="button" data-video="{{ forloop.counter0 }}">Смотреть видео отзыв</button>
						</div>
					</div>
				</div>
                {% endfor %}
			</div>
		</div>
	</section>
{% include 'site/footer.html' %}

templates/site/level2.html
{% load static %}
{% include 'site/head.html' %}
	<nav>
		<div class="container">
			<ul class="navigation">
				<li class="active-nav"><a href="/#services">Наши услуги</a></li>
				<li class="a2"><a href="/#prices">Цены</a></li>
				<li><a href="">Полезные статьи</a></li>
				<li class="a3"><a href="/#replies">Отзывы</a></li>
				<li><a href="/about">О компании</a></li>
				<li><a href="/contacts">Контакты</a></li>
			</ul>
		</div>
	</nav>
	<section class="services">
		<div class="container">
			<h2><b>Выберите</b> интересующую вас услугу</h2>
			<div class="line"></div>
			<div class="services-flex">
                {% for img in imgs %}
                <a href="{% url 'service1' serv.url_name img.service.url_name %}" class="services-item">
					<div class="service-img"><img src="/{{ img.image.url }}"/></div>
					<p>{{ img.service.name }}</p>
                </a>
                {% endfor %}
            </div>
		</div>
	</section>
	<section class="catch-form">
		<div class="catch-form-bg"><img src="{% static 'img/catch-bg.png' %}" alt=""/></div>
		<div class="container">
			<h2><b>Остались вопросы?</b></h2>
			<div class="line"></div>
			<p class="description">Получите бесплатную развёрнутую консультацию специалиста</p>
			<div class="catch-block clearfix">
				<div class="catch-left">
					<form action="{% url 'apply' %}" method="post">
						<input type="text" name="name" placeholder="Введите имя" required="required"/>
						<input type="text" name="phone" placeholder="Введите телефон" required="required"/>
                        <input type="hidden" name="type" value="{{ serv.name }}">
                        {% csrf_token %}
						<textarea name="text" placeholder="Опишите вашу проблему"></textarea>
						<button class="button">Заказать консультацию</button>
					</form>
				</div>
				<div class="catch-right">
					<h5>Вам ответит специалист <br>и проведет полную консультацию <br>по вашему вопросу  </h5>
					<ul>
						<li>Предоставит Вам оптимальный расчёт цены</li>
						<li>Сориентирует по срокам</li>
						<li>Раскажет как правильно сформировать пакет документов</li>
						<li>Даст полное описание процесса</li>
					</ul>
				</div>
			</div>
		</div>
	</section>
{% include 'site/footer.html' %}

templates/site/level3.html
{% load static %}
{% include 'site/head.html' %}
	<nav>
		<div class="container">
			<ul class="navigation">
				<li class="active-nav"><a href="/#services">Наши услуги</a></li>
				<li class="a2"><a href="/#prices">Цены</a></li>
				<li><a href="">Полезные статьи</a></li>
				<li class="a3"><a href="/#replies">Отзывы</a></li>
				<li><a href="/about">О компании</a></li>
				<li><a href="/contacts">Контакты</a></li>
			</ul>
		</div>
	</nav>
	<section class="inner-1">
		<div class="container">
			<h2>{{ serv.block1_header|safe }}</h2>
			<div class="inner-1__flex">
                {% for text in texts %}
				<div class="inner-1__item">
                    <span class="num">{{ forloop.counter }}</span>
					<p>{{ text.text }}</p>
				</div>
                {% endfor %}
			</div>
		</div>
	</section>
	<section class="inner-2">
		<div class="container">
			<h2>{{ serv.block2_header|safe }}</h2>
			<p>{{ serv.block2_text|safe }}</p>
		</div>
	</section>
	<section class="inner-3 dark-bg">
		<div class="inner-3-bg"><img src="{% static 'img/inner-3-bg.png' %}" alt=""/></div>
		<div class="container">
			<h2>{{ serv.block3_header|safe }}</h2>
			<div class="line"></div>
			<div class="inner-3__flex">
                {% for document in documents %}
				<div class="inner-3__item clearfix">
                    <span>{{ forloop.counter }}</span>
					<p>{{ document.text|safe }}</p>
				</div>
                {% endfor %}
			</div>
		</div>
	</section>
	<section class="inner-4">
		<div class="container">
			<h2><b>Цена</b> за данную услугу</h2>
			<div class="line"></div>
			<p class="price">от <b>{{ serv.price }}</b> руб.</p>
			<button class="button inner-conv" data-type="{{ serv.name }}">Оставить заявку</button>
			<p class="text">{{ serv.price_descriptor }}</p>
		</div>
	</section>
	<section class="catch-form">
		<div class="catch-form-bg"><img src="{% static 'img/catch-bg.png' %}" alt=""/></div>
		<div class="container">
			<h2><b>Остались вопросы?</b></h2>
			<div class="line"></div>
			<p class="description">Получите бесплатную развёрнутую консультацию специалиста</p>
			<div class="catch-block clearfix">
				<div class="catch-left">
					<form>
						<input type="text" name="name" placeholder="Введите имя" required="required"/>
						<input type="text" name="phone" placeholder="Введите телефон" required="required"/>
                        <input type="hidden" name="type" value="{{ serv.name }}">
						<textarea name="text" placeholder="Опишите вашу проблему"></textarea>
						<button class="button">Заказать консультацию</button>
					</form>
				</div>
				<div class="catch-right">
					<h5>Вам ответит специалист <br>и проведет полную консультацию <br>по вашему вопросу  </h5>
					<ul>
						<li>Предоставит Вам оптимальный расчёт цены</li>
						<li>Сориентирует по срокам</li>
						<li>Раскажет как правильно сформировать пакет документов</li>
						<li>Даст полное описание процесса</li>
					</ul>
				</div>
			</div>
		</div>
	</section>
{% include 'site/footer.html' %}